const assert = require('node:assert/strict');
const path = require('node:path');

const emptyArtifacts = { observedChats: [], projects: [], styles: [], capabilities: { automaticGeneration: false, modelSwitch: false, liveConnectionVerified: false } };
const identityKey = identity => JSON.stringify([identity.provider, identity.accountId, identity.chatId]);
async function noOverflow(page, width) { assert.ok(await page.evaluate(width => document.documentElement.scrollWidth <= width && document.body.scrollWidth <= width, width), `intro horizontal overflow at ${width}px`); }
async function fixturePng(page, label = '첫 번째 검수 버전') {
  const data = await page.evaluate(label => {
    const canvas = document.createElement('canvas'); canvas.width = 1200; canvas.height = 800;
    const c = canvas.getContext('2d'); c.fillStyle = '#f4f7ef'; c.fillRect(0, 0, 1200, 800); c.fillStyle = '#fff'; c.fillRect(55, 55, 1090, 690);
    c.fillStyle = '#7b9367'; c.font = '20px sans-serif'; c.fillText(`UI FIXTURE · 실제 생성 결과 아님 · ${label}`, 110, 130);
    c.fillStyle = '#354d3d'; c.font = 'bold 52px sans-serif'; c.fillText('회의 준비를 한곳에서', 110, 230);
    c.fillStyle = '#809275'; c.font = '24px sans-serif'; c.fillText('동료와 함께 준비하는 더 편안한 회의', 110, 288);
    ['자료 모으기', '안건 정리', '결정 기록'].forEach((text, i) => { c.fillStyle = '#edf3e6'; c.fillRect(110 + i * 340, 365, 300, 260); c.fillStyle = '#809c68'; c.font = '38px sans-serif'; c.fillText(`0${i + 1}`, 143 + i * 340, 435); c.fillStyle = '#4d6640'; c.font = 'bold 29px sans-serif'; c.fillText(text, 143 + i * 340, 506); c.fillStyle = '#c3d1b5'; c.fillRect(143 + i * 340, 551, 205, 5); c.fillRect(143 + i * 340, 571, 156, 5); });
    return canvas.toDataURL('image/png').split(',')[1];
  }, label);
  return { name: 'intro-ui-fixture.png', mimeType: 'image/png', buffer: Buffer.from(data, 'base64') };
}

async function runIntroChecks({ newPage, mockBridge, fixture, assistanceFixture, origin, screenshotDir, checks }) {
  const screenshots = [];
  const preview = await newPage({ width: 1120, height: 950 });
  await preview.goto(origin);
  await preview.getByRole('button', { name: '소개 자료', exact: true }).click();
  await preview.getByRole('heading', { name: '한 장 소개 자료 만들기' }).waitFor();
  assert.equal(await preview.locator('.intro-template').count(), 3);
  assert.equal(await preview.getByLabel('이 자료를 만들 Codex 채팅', { exact: true }).isEnabled(), false);
  assert.equal(await preview.getByTestId('intro-editor').count(), 0);
  await preview.getByText('브라우저에서는 읽기 전용 미리보기예요.', { exact: false }).waitFor();
  await noOverflow(preview, 1120);
  const landing = path.join(screenshotDir, 'native-ui-intro-templates.png'); await preview.screenshot({ path: landing, fullPage: true }); screenshots.push(landing);
  checks.push('Intro Studio preview has three deterministic labeled templates, empty observed chat list and no fabricated generation');

  const observedPage = await newPage();
  const observedIdentity = { provider: 'codex', accountId: 'observed-local-fixture', chatId: 'fixture-native-only' };
  await mockBridge(observedPage, { ...fixture, sessions: [], slots: [] }, { ...assistanceFixture, tasks: [] }, undefined, { ...emptyArtifacts, observedChats: [observedIdentity] });
  await observedPage.goto(origin);
  await observedPage.getByRole('button', { name: '소개 자료', exact: true }).click();
  await observedPage.getByLabel('이 자료를 만들 Codex 채팅', { exact: true }).selectOption(identityKey(observedIdentity));
  await observedPage.getByTestId('intro-editor').waitFor();
  assert.equal(await observedPage.getByLabel('가장 중요한 한 문장', { exact: true }).inputValue(), '');
  checks.push('authoritative observed native chat is selectable before assistance or workflow records exist');

  const page = await newPage({ width: 1120, height: 1100 });
  const assistance = structuredClone(assistanceFixture);
  const sameChatOtherAccount = { ...structuredClone(assistance.tasks[0]), identity: { ...assistance.tasks[0].identity, accountId: 'second-account-same-chat' } };
  assistance.tasks.push(sameChatOtherAccount);
  await mockBridge(page, fixture, assistance);
  await page.goto(origin);
  await page.getByRole('button', { name: '소개 자료', exact: true }).click();
  const picker = page.getByLabel('이 자료를 만들 Codex 채팅', { exact: true });
  await picker.selectOption(identityKey(assistance.tasks[0].identity));
  await page.getByTestId('intro-editor').waitFor();
  assert.equal(await page.getByRole('button', { name: '소개 자료 요청 복사', exact: true }).isEnabled(), false);
  await page.getByLabel('누구에게 전하나요?', { exact: true }).fill('처음 보는 팀원');
  await page.getByLabel('가장 중요한 한 문장', { exact: true }).fill('회의 준비를 한곳에서');
  await page.getByLabel('핵심 포인트', { exact: true }).fill('자료 모으기\n안건 정리\n결정 기록');
  await page.getByText('원문 발췌와 출처', { exact: true }).click();
  await page.getByLabel('출처 이름', { exact: true }).fill('서비스 소개서 2쪽');
  await page.getByLabel('이 자료에 필요한 원문 발췌', { exact: true }).fill('이 채팅에서 선택한 참고 문구입니다.');
  await page.getByRole('button', { name: '소개 자료 요청 복사', exact: true }).click();
  await page.getByText('AI에 전달된 상태는 아니에요.', { exact: false }).waitFor();
  const copied = await page.evaluate(() => window.__uiTest.clipboard);
  assert.match(copied, /회의 준비를 한곳에서/);
  assert.doesNotMatch(copied, /이 채팅에서 선택한 참고 문구입니다/);
  await page.getByRole('button', { name: '원문 포함 준비 내용 복사', exact: true }).click();
  assert.match(await page.evaluate(() => window.__uiTest.clipboard), /이 채팅에서 선택한 참고 문구입니다/);
  assert.deepEqual(await page.evaluate(() => window.__uiTest.artifacts.projects[0].identity), assistance.tasks[0].identity);
  await page.getByLabel('가장 중요한 한 문장', { exact: true }).fill('');
  assert.equal(await page.getByRole('button', { name: '소개 자료 요청 복사', exact: true }).isEnabled(), false);
  assert.equal(await page.getByTestId('intro-editor').count(), 1);
  await page.getByLabel('가장 중요한 한 문장', { exact: true }).fill('회의 준비를 한곳에서');
  checks.push('Intro request copy persists the exact identity and brief, bounds the prompt, and separately copies user-selected source as reference data without submitting');

  const png = await fixturePng(page);
  await page.getByLabel('생성 결과 PNG', { exact: true }).setInputFiles({ name: 'fake.png', mimeType: 'image/png', buffer: Buffer.from('not a PNG') });
  await page.getByText('실제 PNG 형식의 이미지가 필요해요.', { exact: false }).waitFor();
  assert.equal(await page.getByRole('button', { name: '새 버전 가져오기', exact: true }).isEnabled(), false);
  await page.getByLabel('생성 결과 PNG', { exact: true }).setInputFiles(png);
  await page.getByLabel('이미지에 담긴 문구', { exact: true }).fill('회의 준비를 한곳에서\n자료 모으기\n안건 정리\n결정 기록');
  await page.getByRole('button', { name: '새 버전 가져오기', exact: true }).click();
  await page.getByRole('img', { name: '소개 자료 버전 1', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '이 버전 확정', exact: true }).isEnabled(), false);
  for (const name of ['글자가 읽기 쉽고 잘리지 않아요', '배치와 여백이 의도에 맞아요', '문구와 사실이 원문에 맞아요']) { await page.getByRole('checkbox', { name, exact: true }).check(); await page.waitForFunction(() => !document.querySelector('.intro-review input:disabled')); }
  await page.getByRole('button', { name: '이 버전 확정', exact: true }).click();
  await page.getByRole('button', { name: '확정한 버전', exact: true }).waitFor();
  await page.getByRole('button', { name: 'PNG 저장', exact: true }).click();
  await page.getByText('PNG를 저장했어요.', { exact: false }).waitFor();
  assert.equal(await page.evaluate(() => window.__uiTest.calls.filter(item => item.name === 'artifact_export').length), 1);
  await page.getByLabel('스타일 이름', { exact: true }).fill('나의 세이지');
  await page.getByRole('button', { name: '스타일 저장', exact: true }).click();
  await page.getByText('나의 세이지', { exact: true }).waitFor();
  const savedStyle = await page.evaluate(() => window.__uiTest.artifacts.styles[0]);
  assert.deepEqual(Object.keys(savedStyle).sort(), ['id', 'name', 'style', 'templateId', 'updatedAt']);
  await page.getByRole('button', { name: '소개 자료 즐겨찾기', exact: true }).click();
  await page.waitForFunction(() => window.__uiTest.artifacts.projects[0].favorite);
  await page.getByRole('button', { name: '글 줄이기', exact: true }).click();
  await page.waitForFunction(() => window.__uiTest.artifacts.projects[0].pendingRevision?.kind === 'shorten');
  assert.match(await page.evaluate(() => window.__uiTest.clipboard), /핵심 의미와 사실/);
  await page.getByLabel('생성 결과 PNG', { exact: true }).setInputFiles(await fixturePng(page, '수정한 검수 버전'));
  await page.getByLabel('이미지에 담긴 문구', { exact: true }).fill('회의 준비를 한곳에서');
  await page.getByRole('button', { name: '새 버전 가져오기', exact: true }).click();
  await page.getByRole('img', { name: '소개 자료 버전 2', exact: true }).waitFor();
  const firstId = await page.evaluate(() => window.__uiTest.artifacts.projects[0].versions[0].id);
  await page.getByLabel('나란히 비교', { exact: true }).selectOption(firstId);
  await page.getByRole('img', { name: '비교할 소개 자료 버전 1', exact: true }).waitFor();
  assert.ok(await page.evaluate(() => window.__uiTest.artifacts.projects[0].versions[0].acceptedAt));
  assert.equal(await page.evaluate(() => window.__uiTest.artifacts.projects[0].versions[1].acceptedAt), null);
  await page.evaluate(() => { document.querySelector('.connection-pill').textContent = 'UI 검수용 · 합성 데이터 · 실제 연결 미검증'; });
  const comparison = path.join(screenshotDir, 'native-ui-intro-versions.png'); await page.screenshot({ path: comparison, fullPage: true }); screenshots.push(comparison);
  checks.push('PNG signature validation, user-supplied text, three human checks, immutable accepted version, native export bridge and revision compare work with clearly labeled synthetic images');

  await page.getByLabel('가장 중요한 한 문장', { exact: true }).fill('새 기획의 별도 메시지');
  await page.getByRole('button', { name: '내용 저장', exact: true }).click();
  await page.getByLabel('생성 결과 PNG', { exact: true }).setInputFiles(await fixturePng(page, '다른 기획 검수 버전'));
  await page.getByLabel('이미지에 담긴 문구', { exact: true }).fill('새 기획의 별도 메시지');
  await page.getByRole('button', { name: '새 버전 가져오기', exact: true }).click();
  await page.getByRole('img', { name: '소개 자료 버전 3', exact: true }).waitFor();
  await page.getByLabel('확인할 버전', { exact: true }).selectOption(firstId);
  await page.getByRole('button', { name: '글 줄이기', exact: true }).click();
  await page.waitForFunction(() => window.__uiTest.artifacts.projects[0].pendingRevision?.baseVersionId === window.__uiTest.artifacts.projects[0].versions[0].id);
  assert.equal(await page.getByLabel('가장 중요한 한 문장', { exact: true }).inputValue(), '회의 준비를 한곳에서');
  assert.match(await page.evaluate(() => window.__uiTest.clipboard), /회의 준비를 한곳에서/);
  assert.doesNotMatch(await page.evaluate(() => window.__uiTest.clipboard), /새 기획의 별도 메시지/);
  assert.equal(await page.evaluate(() => window.__uiTest.artifacts.projects[0].versions[2].brief.message), '새 기획의 별도 메시지');
  await page.evaluate(() => {
    const project = window.__uiTest.artifacts.projects[0];
    const version = structuredClone(project.versions[0]);
    version.id = 'fixture-external-import'; version.acceptedAt = null; version.review = { readability: 'pending', layout: 'pending', fidelity: 'pending' };
    version.revisionRequest = project.pendingRevision;
    window.__uiTest.artifactImages[version.id] = window.__uiTest.artifactImages[project.versions[0].id];
    project.versions.push(version); project.pendingRevision = null; project.revision++;
    window.__uiTest.emitEvent('autopets://snapshot', { ...window.__uiTest.state, now: Date.now() });
  });
  await page.waitForFunction(() => [...document.querySelector('#intro-chat').closest('.intro-studio').querySelectorAll('option')].some(option => option.value === 'fixture-external-import'));
  await page.getByLabel('확인할 버전', { exact: true }).selectOption('fixture-external-import');
  await page.getByRole('img', { name: '소개 자료 버전 4', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'PNG 저장', exact: true }).isEnabled(), true);
  checks.push('revision of an older version restores its original brief, preserves later versions, and an externally imported draft appears by refresh and can be exported before acceptance');

  await page.getByLabel('이미지에 담긴 문구', { exact: true }).fill('가져오기 초안');
  await page.getByLabel('누구에게 전하나요?', { exact: true }).fill('다른 채팅에 넘어가면 안 되는 초안');
  await page.getByLabel('추가 수정 요청', { exact: true }).fill('다른 계정에 넘어가면 안 되는 수정');
  await picker.selectOption(identityKey(sameChatOtherAccount.identity));
  assert.equal(await page.getByLabel('누구에게 전하나요?', { exact: true }).inputValue(), '');
  assert.equal(await page.getByLabel('이미지에 담긴 문구', { exact: true }).inputValue(), '');
  assert.equal(await page.getByRole('img', { name: /^소개 자료 버전/ }).count(), 0);
  await page.getByLabel('누구에게 전하나요?', { exact: true }).fill('다른 계정의 고객');
  await page.getByLabel('가장 중요한 한 문장', { exact: true }).fill('두 번째 계정의 새 내용');
  await page.getByLabel('핵심 포인트', { exact: true }).fill('이 계정의 핵심');
  await page.getByRole('button', { name: '최근 스타일 쓰기', exact: true }).click();
  await page.getByText('스타일만 가져왔어요.', { exact: false }).waitFor();
  assert.equal(await page.getByLabel('가장 중요한 한 문장', { exact: true }).inputValue(), '두 번째 계정의 새 내용');
  assert.equal(await page.evaluate(() => window.__uiTest.artifacts.projects[1].brief.sourceText), '');
  assert.deepEqual(await page.evaluate(() => window.__uiTest.artifacts.projects[1].identity), sameChatOtherAccount.identity);
  assert.deepEqual(await page.evaluate(() => window.__uiTest.artifacts.projects[1].style), savedStyle.style);
  checks.push('same chat ID in another account resets unsaved brief/import/revision state; recent approved style reuse preserves only the new account brief');

  await page.evaluate(() => { window.__uiTest.artifactConflictNext = true; });
  await page.getByLabel('가장 중요한 한 문장', { exact: true }).fill('충돌할 편집');
  await page.getByRole('button', { name: '내용 저장', exact: true }).click();
  await page.getByText('artifact revision conflict', { exact: false }).waitFor();
  assert.equal(await page.getByRole('button', { name: '내용 저장', exact: true }).isEnabled(), false);
  assert.equal(await page.evaluate(() => window.__uiTest.artifacts.projects[1].brief.message), '다른 창에서 저장한 내용');
  await page.getByRole('button', { name: '최신 저장 내용 불러오기', exact: true }).click();
  assert.equal(await page.getByLabel('가장 중요한 한 문장', { exact: true }).inputValue(), '다른 창에서 저장한 내용');
  await page.getByRole('button', { name: '저장 상태 다시 확인', exact: true }).click();
  await picker.selectOption(identityKey(assistance.tasks[0].identity));
  await page.getByLabel('확인할 버전', { exact: true }).selectOption(firstId);
  await page.locator('.intro-style-list').getByRole('button', { name: '수정', exact: true }).click();
  await page.getByLabel('스타일 이름', { exact: true }).fill('수정한 스타일 이름');
  await page.getByRole('button', { name: '스타일 변경 저장', exact: true }).click();
  await page.getByText('수정한 스타일 이름', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.__uiTest.artifacts.styles.length), 1);
  await page.locator('.intro-style-list').getByRole('button', { name: '삭제', exact: true }).click();
  await page.waitForFunction(() => window.__uiTest.artifacts.styles.length === 0);
  await page.setViewportSize({ width: 430, height: 1000 });
  await noOverflow(page, 430);
  const compact = path.join(screenshotDir, 'native-ui-intro-compact.png'); await page.screenshot({ path: compact, fullPage: true }); screenshots.push(compact);
  await page.getByRole('button', { name: '이 소개 자료 삭제', exact: true }).click();
  await page.getByRole('dialog', { name: '이 소개 자료를 삭제할까요?', exact: true }).waitFor();
  await page.getByRole('button', { name: '취소', exact: true }).click();
  assert.equal(await page.evaluate(() => window.__uiTest.artifacts.projects.length), 2);
  await page.getByRole('button', { name: '이 소개 자료 삭제', exact: true }).click();
  await page.getByRole('button', { name: '소개 자료 삭제', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.evaluate(() => window.__uiTest.artifacts.projects.length), 1);
  assert.deepEqual(await page.evaluate(() => window.__uiTest.artifacts.projects[0].identity), sameChatOtherAccount.identity);
  assert.equal(await page.evaluate(() => window.__uiTest.calls.some(call => /generate|submit|completion|model.*switch/.test(call.name))), false);
  await page.getByRole('button', { name: '고급 계획·실행 도움 보기', exact: false }).click();
  await page.getByLabel('채팅 선택', { exact: true }).waitFor();
  assert.equal(await page.getByLabel('채팅 선택', { exact: true }).inputValue(), identityKey(assistance.tasks[0].identity));
  checks.push('stale revisions remain visible and cannot overwrite; approved style edit/delete, compact layout and scoped project deletion preserve the other account and never call a model');
  return screenshots;
}

module.exports = { emptyArtifacts, runIntroChecks };
