const assert = require('node:assert/strict');
const path = require('node:path');
const templates = require('../../../packages/contracts/data/roles.json');
exports.runPetLinkChecks = async ({ newPage, mockBridge, fixture, origin, screenshotDir, checks }) => {
  const page=await newPage({width:1120,height:900});
  const value={...structuredClone(fixture),sessions:[],slots:[0,1,2].map(index=>({index,sessionId:null})),petLinks:[{
    version:1,target:{sourceId:'codex-windows-local',threadId:'fixture-parent',cwd:'C:/UI fixture only'},slot:0,revision:1,enabled:true,connected:true,profile:'light',template:templates[1],run:null,
  }]};
  await mockBridge(page,value);await page.goto(origin);
  await page.getByText('채팅 연결됨 · 작업을 기다려요',{exact:true}).waitFor();
  assert.equal(await page.getByText('펫 작업 완료',{exact:true}).count(),0);
  await page.getByRole('combobox',{name:'다음 펫 작업 설정'}).selectOption('careful');
  assert.equal(await page.evaluate(()=>window.__uiTest.state.petLinks[0].profile),'careful');
  await page.evaluate(()=>{window.__uiTest.state.petLinks[0].run={id:'fixture-run',model:'fixture-model',effort:'medium',state:'returned'};window.__uiTest.emitEvent('autopets://snapshot',window.__uiTest.state);});
  await page.getByText('결과 반환 · 실행 기록 확인 필요',{exact:true}).waitFor();
  assert.equal(await page.getByRole('combobox',{name:'다음 펫 작업 설정'}).isDisabled(),true);
  await page.getByRole('button',{name:'도움 끄기',exact:true}).click();
  await page.getByText('새 펫 작업은 꺼져 있어요. 이미 시작한 작업은 계속 확인해요.',{exact:true}).waitFor();
  await page.getByText('결과 반환 · 실행 기록 확인 필요',{exact:true}).waitFor();
  await page.getByRole('button',{name:'도움 켜기',exact:true}).click();
  await page.getByRole('button',{name:'도움 끄기',exact:true}).waitFor();
  await page.getByRole('button',{name:'추적 정리',exact:true}).click();
  await page.getByRole('button',{name:'계속 추적',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.__uiTest.calls.some(c=>c.name==='close_pet_tracking')),false);
  await page.getByRole('button',{name:'추적 정리',exact:true}).click();
  await page.getByRole('button',{name:'이 작업 추적 종료',exact:true}).click();
  await page.getByText('추적 종료 · Codex 작업은 별도로 확인해 주세요',{exact:true}).waitFor();
  assert.equal(await page.getByRole('combobox',{name:'다음 펫 작업 설정'}).isEnabled(),true);
  await page.evaluate(()=>{window.__uiTest.state.petLinks[0].run.trackingClosed=false;});
  await page.evaluate(()=>{window.__uiTest.state.petLinks[0].run.state='waiting';window.__uiTest.emitEvent('autopets://snapshot',window.__uiTest.state);});
  await page.getByText('계획 확인 필요',{exact:true}).waitFor();
  const image=path.join(screenshotDir,'native-ui-explicit-pet.png');await page.screenshot({path:image,fullPage:true});
  const overlay=await newPage({width:420,height:640});await mockBridge(overlay,value);await overlay.goto(`${origin}/?pet=0`);
  await overlay.getByRole('button',{name:'제작 펫 메뉴',exact:true}).click();
  await overlay.getByRole('button',{name:'도움 끄기',exact:true}).waitFor();
  await overlay.evaluate(()=>{window.__uiTest.state.petLinks[0].connected=false;window.__uiTest.emitEvent('autopets://snapshot',window.__uiTest.state);});
  await overlay.getByText('저장됨 · 채팅에서 연결을 다시 확인해 주세요',{exact:true}).first().waitFor();
  checks.push('explicit pet: settings update; unresolved run locks settings; disabled assistance keeps observing; tracking close requires deliberate action; plans await confirmation and restart disconnects');
  return [image];
};
