import type { Snapshot } from '@autopets/contracts/types';
import { isDesktop } from '../../bridge/command';
import { shortPath } from '../../app/shared/format';
import { Badge } from '../tasks/StatusBadge';
import { currentAction, observedActivity } from '../tasks/presentation';
import { Pet } from './Pet';
import { PET_NAMES } from './constants';
import { ExplicitPet } from './ExplicitPet';

export function PetGrid({ snapshot, disconnected, busy, onDetails, onEdit, onUnassign, onOpen, onConnect }: { snapshot: Snapshot; disconnected: boolean; busy: boolean; onDetails: (sessionId: string) => void; onEdit: (sessionId: string) => void; onUnassign: (slot: number) => void; onOpen: (slot: number) => void; onConnect: (slot: number) => void }) {
  return <section className="pet-grid">{snapshot.slots.map(slot => { const explicit = snapshot.petLinks?.find(link => link.slot === slot.index); if (explicit) return <article className={`pet-card pet-card-${slot.index}`} key={slot.index}><ExplicitPet link={explicit} disconnected={disconnected} /><button className="text-button" onClick={() => onOpen(slot.index)}>펫 보기 ↗</button></article>; const session = snapshot.sessions.find(session => session.id === slot.sessionId); return <article className={`pet-card pet-card-${slot.index}`} key={slot.index}><div className="card-top"><span className="pet-name">{PET_NAMES[slot.index]}</span><span className="slot-label">0{slot.index + 1}</span></div><div className="pet-stage"><Pet index={slot.index} activity={observedActivity(session, disconnected)} paused={disconnected || session?.connection === 'unknown'} /></div>{session ? <><Badge session={session} now={snapshot.now} disconnected={disconnected} /><h3 title={session.label}>{session.label}</h3><p className="card-action" title={currentAction(session, disconnected)}>{currentAction(session, disconnected)}</p><p className="card-path" title={session.cwd}>{shortPath(session.cwd)}</p><button className="button card-button" onClick={() => onDetails(session.id)}>작업 카드 열기 →</button><div className="card-options"><button className="text-button" onClick={() => onEdit(session.id)}>작업 설정</button><button className="text-button" disabled={busy} onClick={() => void onUnassign(slot.index)}>연결 해제</button><button className="text-button" onClick={() => void onOpen(slot.index)}>펫 보기 ↗</button></div></> : <><span className="status-badge empty"><i />연결 대기</span><h3>어떤 작업을 맡길까요?</h3><p className="card-action empty-copy">함께할 Codex 작업을 골라주세요.</p><p className="card-path">연결된 환경의 실제 작업만 표시해요.</p><button className="button card-button" disabled={!isDesktop} onClick={() => { onConnect(slot.index); }}>＋ 작업 연결</button></>}</article>; })}</section>;
}
