import type { ReactNode } from 'react';
import { isDesktop } from '../bridge/command';

export type ManagerSection = 'pets' | 'connection' | 'assistance' | 'intro';
export function AppShell({ settings, bound, disconnected, busy, error, onNavigate, onQuit, children, dialogs }: { settings: ManagerSection; bound: number; disconnected: boolean; busy: boolean; error: string; onNavigate: (section: ManagerSection) => void; onQuit: () => void; children: ReactNode; dialogs: ReactNode }) {
  return <div className="app-shell"><aside className="sidebar"><div className="brand brand-logo-lockup"><img className="brand-logo" src="/assets/brand/autopets-logo.svg" alt="AutoPets" width="160" height="37" /><span className="brand-sub">작은 작업 동료</span></div><div className="nav-label">WORKSPACE</div><button className={`nav-item ${settings === 'pets' ? 'active' : ''}`} onClick={() => onNavigate('pets')}><span aria-hidden="true">◈</span><span className="nav-text">나의 펫</span><span className="nav-count">{bound}/3</span></button><button className={`nav-item ${settings === 'connection' ? 'active' : ''}`} onClick={() => onNavigate('connection')}><span aria-hidden="true">⌘</span><span className="nav-text">연결 설정</span></button><button className={`nav-item ${settings === 'assistance' ? 'active' : ''}`} onClick={() => onNavigate('assistance')} aria-label="자동 도움"><span aria-hidden="true">✦</span><span className="nav-text">자동 도움</span></button><button className={`nav-item ${settings === 'intro' ? 'active' : ''}`} onClick={() => onNavigate('intro')} aria-label="소개 자료"><span aria-hidden="true">▧</span><span className="nav-text">소개 자료</span></button><div className="sidebar-bottom"><span className="local-indicator" />이 PC에서만 실행<p>작업의 흐름을 가까이,<br />필요한 순간에 확인해요.</p><button className="text-button danger-text" disabled={!isDesktop || busy} onClick={onQuit}>AutoPets 종료</button><span className="version">LOCAL MVP · 0.1</span></div></aside>
    <main className="main-content"><header className="topbar"><span>YOUR LITTLE WORKSPACE</span><span className={`connection-pill ${disconnected ? 'offline' : ''}`}><i />{!isDesktop ? '브라우저 미리보기 · 연결 없음' : disconnected ? '브리지 연결 확인 필요' : '로컬 앱 실행 중'}</span></header>{error && <div className="error" role="alert">{error}</div>}
{children}</main>{dialogs}</div>;
}
